<%@ page language="java" contentType="text/html; charset=UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>

<style>
/* ----------------------------------------------
 * Generated by Animista on 2023-2-2 16:36:11
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-up-center
 * ----------------------------------------
 */
@-webkit-keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0.5);
            transform: scale(0.5);
  }
  100% {
    -webkit-transform: scale(1);
            transform: scale(1);
  }
}
@keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0.5);
            transform: scale(0.5);
  }
  100% {
    -webkit-transform: scale(1);
            transform: scale(1);
  }
}

.scale-up-center {
	-webkit-animation: scale-up-center 0.4s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
	        animation: scale-up-center 0.4s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
}


#loginDiv{
	margin-top: 250px; 
}

input:focus, select:focus, textarea:focus {
    border: 2px solid #4f9dff !important;
    outline: none;
}
.titleText{
	text-align: center;
	margin-top: -40%;
}

.form-control{
	margin-left: 10px;
	width: 95%;
}

.titleName {
	margin-left: 8px;
	margin-top: 5px;
	font-size: 1.2em;
	font-weight: 600;
}

.loginForm22{
	margin: 5%;
	z-index: 10px;
	padding: 5%;
}

.text-center{
	margin: 5%;
}

.joinTitle{
	font-weight: 600;
}

.logo{
	width: 60%;
}


.joinDiv{
	padding: 5%;
}

.logoLogin{
	margin-top: 10%;
	margin-bottom: 10%;

}

.form-check-input:checked {
    background-color: #71aaf1;
    border-color: #71aaf1;
}


body{
	background: url("../../resources/images/appImg/appLoginBack.jpg");
	background-size: cover;
}


</style>
<!-- 로그인 -->
<body>

	<div id="msg" style="display:none;">${msg}</div>

	<div id = "loginDiv" class = "scale-up-center">
		<div class="position-relative pt-4 py-5 mb-1 titleText">
<!-- 			<h3 class="text-white"> -->
<!-- 				<b>환영합니다!</b> -->
<!-- 			</h3> -->
<!-- 			<h5 class="text-white"> -->
<!-- 				<b>AlphaPet 서비스를 이용해주셔서 감사합니다.</b> -->
<!-- 			</h5> -->
		</div>
		<div class="card overflow-hidden mt-2 loginForm22">
	
		<div align="center">
			<img class="logo logoLogin" src="${pageContext.request.contextPath }/resources/images/appImg/alphaPet.png" />
<%-- 			<img class="logo2 logoLogin2" src="${pageContext.request.contextPath }/resources/images/appImg/appBack.gif" /> --%>
		</div>
	
		<form action="/appLogin" method="post">
				<div class="mb-3">
                    <label for="username" class="form-label titleName"><b>회원 ID</b></label>
                    <input type="text" class="form-control" name="userId" value="" placeholder="아이디를 입력해주세요.">
                </div>
                <div class="mb-3">
                    <label for="userpassword" class="form-label titleName"><b>비밀번호</b></label>
                    <input type="password" class="form-control" name="userPw" value="" placeholder="비밀번호를 입력해주세요.">        
                </div>
                
               	<div class="mt-3">
                    <button class="btn btn-info w-100 waves-effect waves-light" type="submit">로그인</button>
                </div>
		</form>
		<div style="text-align: center;">
		<br>
		<a href="#" style="color: #4f9dff;"><b>아이디찾기</b></a>
		<a id= "joinBtn">회원가입</a>

		</div>
	</div>
	</div>
	
	
<!-- 	회원가입 -->
	<div class="wrapper" id = "joinDiv" style = "display: none">
		<div class="card-body">
		<div class="card">
		
		<hr>
			<div align="center">
					<img class="logo" src="${pageContext.request.contextPath }/resources/images/appImg/alphaPet.png" />
			</div>
			<div>
				<h4 align="center"><b>회원가입</b></h4>
				<h6 align="center"><b>회원정보를 입력해주세요.</b></h6>
			</div>
		<hr>
			<form id="joinForm">
				<div>
					<label class="form-label titleName"><i class="dripicons-dot danger"></i>아이디</label>
					<input type="text" class="form-control" name="userId" placeholder="아이디를 입력해주세요."><br>
				</div>
				<div>
					<label class="form-label titleName"><i class="dripicons-dot danger"></i>비밀번호</label>
					<input type="password" class="form-control" name="userPw" placeholder="영문+숫자 8-15자리"><br>
				</div>
				<div>
					<label class="form-label titleName"><i class="dripicons-dot danger"></i>이름</label>
					<input type="text" class="form-control" name="userName" placeholder="이름을 입력해주세요."><br>
				</div>
				<div>
					<label class="form-label titleName"><i class="dripicons-dot danger"></i>전화번호</label>
					<input type="text" class="form-control" name="userTel" placeholder="010-0000-0000" ><br>
				</div>
<!-- 				<div> -->
<!-- 					<label class="form-label titleName"><i class="dripicons-dot danger"></i>이메일</label> -->
<!-- 					<input type="email" class="form-control" name="userMail" placeholder="alphaPet@aaa.com"><br> -->
<!-- 				</div> -->
<!-- 				<div> -->
<!-- 					<label class="form-label titleName"><i class="dripicons-dot danger"></i>주소</label> -->
<!-- 					<input type="text" class="form-control" name="userAddr1"><br> -->
<!-- 				</div> -->
<!-- 				<div> -->
<!-- 					<label class="form-label titleName"><i class="dripicons-dot danger"></i>상세주소</label> -->
<!-- 					<input type="text" class="form-control" name="userAddr2"><br> -->
<!-- 				</div> -->
<!-- 				<div> -->
<!-- 					<label class="form-label titleName"><i class="dripicons-dot danger"></i>우편번호</label> -->
<!-- 					<input type="text" class="form-control" name="userZip"><br> -->
<!-- 				</div> -->
				<button type="button" class="btn btn-info w-100 waves-effect waves-light" id="submitBtn">가입하기</button>
			</form>
		</div>
	</div>
	</div>
	
</body>
<script>
	let msg = document.getElementById("msg").innerHTML;

$(function(){
	if(msg != ""){
		setTimeout(() => Swal.fire({
			icon: "error",
			title: '아이디 또는 비밀번호가 틀렸습니다.',
	        confirmButtonColor: '#3085d6',
	        confirmButtonText: '확인',
  		 	backdrop: true,
		}), 1500);
		
	}
	
	document.getElementById("headerDiv").style.display = "none";
	document.querySelector(".header").style.display = "none";
	$("#menuBar").css("display", "none");

	var loginDiv = document.querySelector("#loginDiv");
	var joinDiv = document.querySelector("#joinDiv");
	
	var joinForm = document.querySelector("#joinForm");
	var joinBtn = document.querySelector("#joinBtn");
	var submitBtn = document.querySelector("#submitBtn");

	var backBtn = document.querySelector("#backBtn");
	
	//회원가입 클릭
	$(joinBtn).on("click", function(){
		$(loginDiv).css("display", "none");
		$(joinDiv).css("display", "block");

		$(joinDiv).attr("class", "wrapper scale-up-center");
		
	})
	
	//회원가입 완료버튼
	$(submitBtn).on("click", function(){
		var formData = new FormData(joinForm);
		
		$.ajax({
			url : "/appJoin",
			type : "post",
			data : formData,
			processData: false,
	        contentType: false,
			success : function(){
	    	   Swal.fire({
	    		   title: '회원가입 되었습니다.',
	    		   icon: 'success',
	    		   confirmButtonText: '확인', // confirm 버튼 텍스트 지정
	    		}).then(result =>{
					$(loginDiv).css("display", "");
					$(joinDiv).css("display", "none");
					formReset();
	    		})
			},
		    error:function(request,status,error){
		    	 Swal.fire({
	    		   title: '아이디가 중복되었습니다.',
	    		   icon: 'error',
	    		   confirmButtonText: '확인', // confirm 버튼 텍스트 지정
	    		}).then(result =>{
	    			document.getElementById('#joinForm input[name="userId"]').focus();
	    		})
		    }
		})
	})
	
	$(backBtn).on("click", function(){
		$(loginDiv).css("display", "");
		$(joinDiv).css("display", "none");	
	})
	
	
	//폼 리셋
	function formReset(){
		$(joinForm).each(function() {
			this.reset();
  		});
	}
})
</script>
